/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'damianoneill' at '02/10/15 13:51' with Gradle 2.6
 *
 * @author damianoneill, @date 02/10/15 13:51
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
